#!/usr/bin/env bash

set -e

export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export IMA_SDK_DIR=$DIR/../skale-ima-sdk

: "${SDK_PRIVATE_KEY?Need to set SDK_PRIVATE_KEY}"
: "${SDK_ADDRESS?Need to set SDK_ADDRESS}"

: "${TEST_PRIVATE_KEY?Need to set TEST_PRIVATE_KEY}"

TEST_PRIVATE_KEY=$TEST_PRIVATE_KEY PRIVATE_KEY_FOR_SCHAIN=$SDK_PRIVATE_KEY ACCOUNT_FOR_SCHAIN=$SDK_ADDRESS ACCOUNT_FOR_ETHEREUM=$SDK_ADDRESS PRIVATE_KEY_FOR_ETHEREUM=$SDK_PRIVATE_KEY URL_W3_ETHEREUM=http://ganache:8545 bash $IMA_SDK_DIR/run_compose.sh
